### ISSUE TITLE
This plugin is now just a bloated, shameless advertisement for MemberPress?

### ISSUE THREAD

**Issue by thomasfw** [caseproof/members#9]
The WordPress ecosystem is becoming a cesspit of developers/teams like yours, buying up popular open source plugins in order to hijack the dashboard and push your paid plugins on unsuspecting users.

You'll be more than aware that this plugin has long been the go-to for dynamic role/cap management. The (disabled by default) basic content permission features were clearly secondary to the main function, as evident from the [plugin's description](https://wordpress.org/plugins/members/):

> "Members is a plugin that extends your control over your blog. It’s a user, role, and capability editor plugin that was created to make WordPress a more powerful CMS.
>  It puts you in control over permissions on your site by providing a user interface (UI) for WordPress’ powerful role and cap system, which is traditionally only available to developers who know how to code this by hand."

If you genuinely can't see why your latest updates might not be totally welcome, then i'll happily take the time to go through the reasons why. If you're not bothered, i'll stop wasting my time and will just fork/maintain the original plugin instead.

**Comment by renventura** [comment]
@thomasfw Perhaps we have a different definition of "hijacking" the dashboard. Members 3.0 was designed, first and foremost, to improve the admin UI and offer premium features for **free**. We did not add anything intrusive. Further, no core functionality of Members was altered or hindered in any way. Members now offerers far more free features than it did before (as well as an improved UI), and we believe users will appreciate that the most.

**Comment by thomasfw** [comment]
@renventura You're right, I think we do. For a start, the original plugin enabled it's core functionality in an unobtrusive way, with a single _'Members'_ subpage under the Settings menu. The _'Roles'_ and _'Add New Role'_ pages were sensibly displayed under the _'Users'_ menu.

We now have an entirely separate and unnecessary menu item dedicated to this plugin. On it's own this is maybe a slight annoyance, but coupled with the numerous subpages - _'Add-ons'_ (read: "bloat", in green no less), _'Payments'_, _'About Us'_ - that mostly serve no purpose other than to advertise your premium offerings, I don't see how this is anything other than intrusive.

Case in point 1:

<img width="1467" alt="Screenshot 2020-04-14 at 15 52 00" src="https://user-images.githubusercontent.com/7723105/79239134-1a3b1680-7e68-11ea-8401-57d374fa98ce.png">

Case in point 2:

<img width="1465" alt="Screenshot 2020-04-14 at 15 52 27" src="https://user-images.githubusercontent.com/7723105/79239175-26bf6f00-7e68-11ea-83c5-74d40f6d08cf.png">

And again, another issue here is that the main features of the plugin have little to do with site membership. This was first and foremost a tool to allow dynamic management of site roles/caps (something it does very well), and i'd imagine this is where the majority of installs come from. 

If core functionality is unaltered, then why do I no longer have the option to disable the optional widgets (again, previoulsy disabled by default)? Giving my clients the ability to add a widget that lists all users on their large website is totally pointless at best, and at worst a security issue.

**Comment by renventura** [comment]
> For a start, the original plugin enabled it's core functionality in an unobtrusive way, with a single 'Members' subpage under the Settings menu. The 'Roles' and 'Add New Role' pages were sensibly displayed under the 'Users' menu.

I think this is a subjective point. There were also users (e.g new users) who couldn't easily locate the various settings spread across different areas in the admin, so consolidating the settings made sense to simplify the UI.

> On it's own this is maybe a slight annoyance, but coupled with the numerous subpages - 'Add-ons' (read: "bloat", in green no less), 'Payments', 'About Us' - that mostly serve no purpose other than to advertise your premium offerings, I don't see how this is anything other than intrusive.

The mentions of MemberPress are restricted to select locations, and are not displayed all over the admin. We dedicate time and resources to maintain and support a free plugin. The use of a few calls to action to support our premium product will help us continue dedicating those resources.

> And again, another issue here is that the main features of the plugin have little to do with site membership.

Again, this is more subjective. There are many people who use Members to protect content based on user role. The main difference between doing this with Members vs. MemberPress is that MemberPress allows for accepting payments to do it - something people may want to do at some point. 

> If core functionality is unaltered, then why do I no longer have the option to disable the optional widgets (again, previoulsy disabled by default)?

We made this decision because it made sense to us to enable these widgets by default. Tying use of the widgets to enabling a setting introduced an extra step in the process, so enabling them by default was meant to improve the user experience. That said, there are filters you can use to disable them, if needed:

```php
add_filter( 'members_login_widget_enabled', '__return_false' );
add_filter( 'members_users_widget_enabled', '__return_false' );
```

I'll leave this off with letting you know that we completely understand your concern, @thomasfw. Our goal was to keep our calls to action as simple as possible, such as by not cluttering the admin with notices, or requiring manual steps to dismiss things. 

We want to support and maintain a valuable, useful tool for whoever needs it. MemberPress is one of our products that allows us to devote the resources for doing that, so introducing the calls to action is meant to help with the effort moving forward.

As Members is open-source, you are certainly free to maintain your own version if that will better serve your own needs. We will continue to support and maintain Members, so you're also free to use it and simply ignore our mentions of MemberPress. Whichever works best for you.

That said, I'm going to close this out.

All the best,

Ren

**Comment by andremacola** [comment]
I am really disappointed with the direction of the plugin. There is in fact some bloated stuff like what happened to YOAST.

After upgrading from 2.2.0 to 3.0.4 my website is now returning critical errors on Members settings page and do not work properly.

Right now I'm thinking to fork the 2.2.0 version to continue the work.

**Comment by thomasfw** [comment]
@andremacola agreed, it's a shame this practice is getting more and more common. We've forked the original plugin and are maintaining a stripped back version, so it may or may not fit your needs - [freshsystems/wp-permission-manager](https://github.com/freshsystems/wp-permission-manager)

**Comment by Gunstick** [comment]
And this giant ad covering a whole page, well I got rid of it with

`cp /dev/null wp-content/plugins/members/img/Members-header.svg`
